{
 "title": "New dashboard",
 "description": "offer",
 "time": { "from": "2023-12-11T15:29:46.886Z", "to": "2023-12-11T15:39:46.886Z" },
 "panels": [
  {
   "title": "process start time as unix timestamp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_start_time_seconds ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mean response time for find without index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/find/staff/\"}[1m])/rate(http_request_duration_seconds_count{path=\"/find/staff/\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/find/staff/\"}[1m])/rate(http_request_duration_seconds_count{path=\"/find/staff/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds.",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" },
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mean response time for find by index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/staff/1\"}[1m])/rate(http_request_duration_seconds_count{path=\"/staff/1\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/staff/1\"}[1m])/rate(http_request_duration_seconds_count{path=\"/staff/1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of seconds since 1970 of last garbage collection.",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_last_gc_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean response time for get big amount of data (1200 records)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/v1/book/all\"}[1m])/rate(http_server_requests_seconds_count{uri=\"/api/v1/book/all\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/v1/book/all\"}[1m])/rate(http_server_requests_seconds_count{uri=\"/api/v1/book/all\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of goroutines that currently exist.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" },
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of allocated objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" },
    { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap % used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes)*100/sum(go_memstats_heap_sys_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes)*100/sum(go_memstats_heap_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}